### ISSUE TITLE
live-installer: Improvements in user page

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#10]
When installing Cindy, where you enter your credentials, one of the input boxes was called "hostname" It has since been renamed to "Computer's Name" in Debbie. 

But type in a capital letter for your computer name , and an error message appears saying "The hostname must be lower case". 

Should the error message and the input box prefix not have the terminology - either Computer's Name or Hostname.

**Comment by callagg2** [comment]
Related to the above issue of an incorrect entry for computer name. 

When I receive an error, all but one entries has a correct symbol at the end, should the input box with the incorrect entry not have a red X at the end. 

Further, the cursor should default back to the input box with the incorrect entry, not the input box following it.

**Comment by clefebvre** [comment]
Fixed by:

https://github.com/linuxmint/live-installer/commit/3cb688e2e2456fc11c2e7d3ee7031cfe98a65a19
https://github.com/linuxmint/live-installer/commit/c3c9299891f39ec06d7c7daf658a92cf22c75ff0
