### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#11]
On the installer, and on the desktop background image, we have the old Linux Mint "leaf" logo.
Is this being updated for the release?

**Comment by cer-0** [comment]
Not sure, LM 19.3 has the same background, and probably the same installer image.

**Comment by clefebvre** [comment]
Hi @callagg2 

No this is fine. We worked on the logo and used the inner part as the identifiable piece, so that we could use it in more contexts and more surrounding shapes. That doesn't mean the leaf can't be used anymore.
