### ISSUE TITLE
Redshift

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#13]
Redshift did not turn automatically, I had to select Redshift from the Start menu, and only then did it start. 

I think maybe it should be automatic in Start-up Applications or include it in the Welcome Screen to activate it or explain how to do this in the Installation Notes. (Again, that is just my opinion as a relatively inexperienced user)

**Comment by clefebvre** [comment]
Thanks I appreciate your opinion and suggestion on this. However, I think it's discoverable enough considering the number of people who use it. It was popular enough for us to install by default but it's not something we necessarily want to run out of the box or highlight in the first screen people get to see. If we shove too much into this, people just won't read it anymore.

**Comment by clefebvre** [comment]
In terms of ease of use, redshift-gtk provides a checkbox for autorun so it's really easy to set up, even for users who aren't familiar with the system settings (i.e. they don't need to go in Settings -> Startup Applications).
