### ISSUE TITLE
lsb (>= 3.2) epson printer workforce k101

### ISSUE THREAD

**Issue by jozeferreira** [linuxmint/lmde-4-cinnamon-beta#14]
The old problem with lsb-base in this release when installing my epson printer workforce k101 . I solved installing lsb-compat_9.20161125_amd64.deb from debian packages. I believe that others  versions will work well too. Please, fix this problem. There are many users suffering with this question.
Tanks and congratulations. Very nice release.

**Comment by clefebvre** [comment]
Can we get more information about the issue and the fix you're recommending? sorry, I'm not aware of the problem..

**Comment by jozeferreira** [comment]
**1 - Try to install epson driver printer k101**
 http://download.ebz.epson.net/dsc/op/stable/debian/dists/lsb3.2/main/binary-amd64/epson-inkjet-printer-k100-k200-series_1.0.0-1lsb3.2_amd64.deb.
gdebi will return a error
jose@escritorio:~/Dados/Downloads/Epson K100$ gdebi epson-inkjet-printer-k100-k200-series_1.0.0-1lsb3.2_amd64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Este pacote não pode ser desinstalado
Dependency is not satisfiable: lsb (>= 3.2)

**2 - Verify packages lsb on lmde3 and 4**

LMDE4
jose@escritorio:~/Dados/Downloads/Epson K100$ apt-cache search lsb-
lsb-base - funcionalidade de script init da Linux Standard Base
lsb-release - utilitário para relatar a versão do Linux Standard Base
debian-goodies - Small toolbox-style utilities for Debian systems
liblinux-distribution-perl - module for detecting the running Linux distribution
jose@escritorio:~/Dados/Downloads/Epson K100$ 

LMDE3
jose@jose:~$ apt-cache search lsb-
liblinux-distribution-perl - module for detecting the running Linux distribution
lsb-base - Linux Standard Base init script functionality
lsb-compat - Linux Standard Base Compatibility
lsb-release - Linux Standard Base version reporting utility

Note: lsb-compat  is not present on lmde4.

**3- How I solved?**
I installed the package lsb-compat e my printer worked well.

I noted this problem when debian buster was released. I fell that this problem on lmde4 was inherited from it.

Tank you very much by attention.
I'm done to new questions.

**Comment by clefebvre** [comment]
Hi @jozeferreira, yes the problem could be attributed to Debian not shipping lsb, but they removed support voluntarily in 2015... I'd argue it's Epson's responsability to update their package and not depend on this.

Which version of lsb-compat did you install? Where did you get the deb from?

**Comment by jozeferreira** [comment]
Hy @clefebvre. Get here:  https://packages.debian.org/stretch/lsb-compat

**Comment by clefebvre** [comment]
Thanks, I'll add this to the release notes.
