### ISSUE TITLE
live-installer: Automated mode doesn't support NVMe

### ISSUE THREAD

**Issue by edover2019** [linuxmint/lmde-4-cinnamon-beta#15]
-Patrition creation takes a while when installing LMDE4 on an NVMe drive with LVM and LUKS options. Then it starts to proceed with the install. It copies some files, then shows an error that there is not enough disk space and that bootloader has to be installed manually. This happens when installing LMDE 4 on a disks with ample space available.

-Installing LMDE4 on an NVMe drive without LUKS and LVM options results in low disk space and bootloader install errors as well. OS does not install properly.

-Installing LMDE4 on a SATA drive with, or without LVM and LUKS is successful

-These problems all occur when installing LMDE4 on physical and virtual machines using NVMe drives.

-LMDE4 installer seems to have a problem with installing onto an NVMe drive.

-Other Linux operating systems install successfully onto the NVMe drive with, or without LVM and LUKS options.
![Screenshot at 2020-02-25 18-35-03](https://user-images.githubusercontent.com/53305481/75285177-0c74f780-580e-11ea-865e-6ee9343d9d07.png)
![Screenshot at 2020-02-25 18-22-56](https://user-images.githubusercontent.com/53305481/75285179-0da62480-580e-11ea-8ea5-fbe1e7c3da4e.png)

**Comment by orcus-de** [comment]
might (or might not) help to sort it out - at least worth a try:

We more often see people at irc having issues with nvme .m2  ssds most of them using ubuntu-mint - where in most cases the ssds are not detected at all.
The typical reason is, that the bios is set to sata/raid-mode instead of ahci. After switching to ahci-mode most (all?) people succeed in using the ssd.

The downside is - people using a dual-boot setup with windows being installed in sata-mode, people have to fix their windows-install additionally (missing ahci-drivers) to be
able to switch to ahci-mode entirely

cheers orcus

**Comment by clefebvre** [comment]
@edover2019 can you show the summary screen and the terminal output (you can get that by launching the installer from the command line: sudo live-installer).

**Comment by clefebvre** [comment]
Actually, no need.. I can reproduce this here. The partition names aren't correct. It should be an easy fix.

**Comment by Phil995511** [comment]
I also had this indication once but after reboot everything worked fine.

**Comment by clefebvre** [comment]
Should be fixed by https://github.com/linuxmint/live-installer/commit/7ab8ed68724327f5a873c1dabbc1d811b7b03abb. I'll have to run tests again to make sure.

**Comment by barthohomeautomation** [comment]
I attempted an install on a ZenBook today and ran into the same issues as noted above. I attempted a second install selecting the option to encrypt the disk option. In this case the install completed but would not boot. I made the changes in the above noted ticket, and this did not resolve the issue.

**Comment by clefebvre** [comment]
I can confirm this change fixes NVMe with simple automated installs (i.e. no LVM, no LUKS). Tested in EFI mode in Virtualbox.

I'll test LVM and LUKS now.

**Comment by clefebvre** [comment]
A new version of the installer is available in the repositories, containing this change.

**Comment by clefebvre** [comment]
Successful test also for EFI+NVME+Automated+LVM in Virtualbox.

Note that EFI is mandatory in Virtualbox when using NVME.

**Comment by clefebvre** [comment]
Successful test also for EFI+NVME+LVM+LUKS in Virtualbox.

I noticed race conditions issues between parted, sync and mkfs though, I'll fix that as well.

**Comment by barthohomeautomation** [comment]
I downloaded a fresh install iso, performed an update and installed the live-installer update, and attempted to perform an install. It failed with the same low disk space error.

**Comment by clefebvre** [comment]
@barthohomeautomation can you start it from the terminal (sudo live-installer) and provide the output?
