### ISSUE TITLE
LMDE 4 did not install video driver

### ISSUE THREAD

**Issue by WendellF** [linuxmint/lmde-4-cinnamon-beta#17]
On first boot-up on VirtualBox 5.2.32, it notified that the video driver had not been installed.  
I don't know if this is normal on a VM.  Not sure if the Cinnamon core dump below is related but the Linux Screen Driver was mentioned. 

Feb 25 23:12:01 lmde-beta pulseaudio[1248]: E: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.TimedOut: Fai
Feb 25 23:12:01 lmde-beta brltty[447]: DBus error: send message: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': t
Feb 25 23:12:01 lmde-beta brltty[447]: brltty: DBus error: send message: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.b
Feb 25 23:12:01 lmde-beta kernel: input: BRLTTY 5.6 Linux Screen Driver Keyboard as /devices/virtual/input/input9
Feb 25 23:12:01 lmde-beta brltty[447]: Linux Screen Driver:
Feb 25 23:12:01 lmde-beta brltty[447]: brltty: Linux Screen Driver:
Feb 25 23:12:01 lmde-beta systemd[1]: Condition check resulted in Bluetooth service being skipped.
Feb 25 23:12:01 lmde-beta dbus-daemon[480]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested b
Feb 25 23:12:01 lmde-beta systemd-logind[461]: Watching system buttons on /dev/input/event8 (BRLTTY 5.6 Linux Screen Driver Keyboard)
Feb 25 23:12:06 lmde-beta systemd[1]: systemd-hostnamed.service: Succeeded.
Feb 25 23:12:07 lmde-beta systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Feb 25 23:12:16 lmde-beta dbus-daemon[985]: [session uid=1000 pid=985] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-te
Feb 25 23:12:16 lmde-beta systemd[886]: Starting GNOME Terminal Server...
Feb 25 23:12:16 lmde-beta dbus-daemon[985]: [session uid=1000 pid=985] Successfully activated service 'org.gnome.Terminal'
Feb 25 23:12:16 lmde-beta systemd[886]: Started GNOME Terminal Server.
Feb 25 23:12:26 lmde-beta dbus-daemon[480]: [system] Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
Feb 25 23:12:26 lmde-beta brltty[447]: brltty: DBus error: send message: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.b
Feb 25 23:12:26 lmde-beta brltty[447]: brltty: console control error 5: fd=8 vt=1 op=0X5603: Input/output error
Feb 25 23:12:26 lmde-beta brltty[447]: DBus error: send message: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': t
Feb 25 23:12:26 lmde-beta brltty[447]: console control error 5: fd=8 vt=1 op=0X5603: Input/output error

**Comment by Phil995511** [comment]
A VirtualBox VM machine don't install a Nvidia driver, that's normal !!!

For fully use its performance you must add the package "Oracle_VM_VirtualBox_Extension_Pack-6.1.0"

The only one card / driver disponible with VirtualBox is : VMware SVGA II adapter / driver

**Comment by clefebvre** [comment]
For best results use the VMSVGA display driver (in your VM settings). Make sure you're running the latest Virtualbox (6.1) also.
