### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-4-cinnamon-beta#18]
If you prepare yours partitions before installation from Linux Mint 19.3 with Gnome-Disk, you are obliged to give a name (label) to the partitions that you are going to create. => After when you install LMDE 4 (without using Gparted to partition again, only with using Gnome-Disk), the installation is done well, but on reboot the OS refuses to launch.

Prepare it with Gparted without partition name (label) everything works fine on reboot.

Regards.

**Comment by clefebvre** [comment]
Sorry Phil,

I can't reproduce this issue. Something else must have been at play here than the labels. We fixed quite a few corner case issues in the installer since the BETA, maybe it's one of them.
