### ISSUE TITLE
LMDE 4 beta not sourcing ~/.profile ~/.xprofile /etc/profile /etc/xprofile

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/lmde-4-cinnamon-beta#2]
LMDE 4 beta not sourcing on startup:
~/.profile
~/.xprofile
/etc/profile
/etc/xprofile

reported for lmde 3 already see -> https://github.com/linuxmint/linuxmint/issues/120
I did update a private fix to cover LMDE 4 beta too: 
https://www.orcus.de/main_workarounds/lmde3_fix_profile.htm

might be easiest to see the difference

In the essence the fix does add
/usr/sbin/lightdm-session (the wrapper)
/usr/lib/lightdm/config-error-dialog.sh (the internal used helper)
I did grab both files from a mint 19.0 cinnamon install

And does set/activate in /etc/lightdm/lightdm.conf
session-wrapper=lightdm-session

**Comment by clefebvre** [comment]
Hi @orcus-de,

What's the situation in this regard in Debian 10 Buster? That's the kind of things I'd rather leave to upstream.

**Comment by orcus-de** [comment]
Hi Clem,

I'll have a look at Buster later tonight ...

Yes, I understand that Mint cannot solve all upstream problems. And yes - users can fix the issue with my provided tool themselves, but most of them will not even notice it being there...

Regardless of it is an upstream problem or not, the current state is unpleasant for users:

If you have to set up the environment - PATH or exported variables - for your xsession (per user), almost every common tutorial will recommend the use of ~/.profile - which just doesn't work with Linux Mint since LMDE 3 switched to lightdm.

And yes again - there are other ways to work around the problem. But: configuring the environment using a standard mechanism is such a basic thing that shouldn't be broken.

The debugging and preparatory work is done since LMDE 3. You just have to go through it again and with a little luck you can just adapt it.

PS: I know that I can be a pain
PPS: I love the new lmde4 version // it's looking great to me and is a big step forward.

**Comment by orcus-de** [comment]
Hi Clem,

checked with current buster - it's the same drame there (which you likely knew before yourself).

Fun-fact: after patching the version-test of my tool, to accept buster, it's fixing the issue there too - including automatically adding a ~/bin -folder to the PATH if being available ...(a detail of lightdm initi I didn't mention before)

I guess I know what might be your answer next .. :-1: 

**edit/added:**
Digging at https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/794315  turns out to be a dead-end here (wontfix):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=636108

I cant access the ubuntu-fix (and have no intention to sign up there).

**Comment by clefebvre** [comment]
Hi Orcus,

Yes, ultimately this is something for upstream to consider and it looks like it's been done already. I kinda agree with them. I like using /etc/X11/Xsession.d myself, not only because it's explicitly for the X session, but also because of the flexibility the directory gives... it allows packages and/or users to define their own separate files and order them appropriately.
