### ISSUE TITLE
VM installation

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-4-cinnamon-beta#20]
If you want to make a VM installation > you double click on "Install Linux Mint", on 800x600 , the buttons to click to advance through the installation are not visible.

You must use "TAB" to advance blind...

An installer option without graphics options (text format only) would be welcome.

If I start the install in LMDE 4 compatibility mode, after the boot from the live CD, I'm on 5632 x 5632 default resolution :) 

After install, at reboot, I have a error "impossible to unmont the partition". => force reboot and all is ok.

With "Oracle_VM_VirtualBox_Extension_Pack-6.1.0" instaled all resolution are available to 2560 x 1600, but not 1920 x 1080 ?! 

The maximum resolution of my monitor is 2560 x 1440.

**Comment by martindurant** [comment]
As described in the release notes, you can hold the <TAB> key to move windows around the screen where the resolution is not high enough for them to fit

**Comment by Phil995511** [comment]
Thank you Martin for your indication, ALT not work for this fonction on Virtual Machine but after tests ALT GR (right ALT) work.

This is a slightly complicated way of doing things and it is not very user friendly.

I had found as a solution an install in compatibility mode.

After adjusting to a reasonable resolution (2048 x 1152 or less), there is no longer any need to crop the image during the entire installation process, unlike the above proposed solution. But I don't find this solution elegant enough either.

**Comment by clefebvre** [comment]
Hi Phil,

There's not much we can do.. I suppose we could detect the VM and live session and force a higher resolution out of the box.. I'll add to the roadmap but I'm not promising anything.

When using Virtualbox I suggest you select the VMSVGA driver. Also once in the live session you can use the Display Settings to bump the resolution.

**Comment by Phil995511** [comment]
Hello,

Too bad you cannot remedy it because it is really very impractical...

Regards

**Comment by clefebvre** [comment]
We might, we've got a fix in place.

**Comment by Phil995511** [comment]
You decide what you want to do or not... 

Personally I'm fed up with the incessant update system inherited from Ubuntu, I don't think I will be using more Mint 19.x or 2x.x again in the future.

I would have liked the management of dual GPUs under LMDE, which Gnome brings with version 3.36, you don't want to do it before LMDE 5, in 2 years, according to your explanations. For this reason I finished using Mint, I am now only under Debian. Unless you change your mind, which will surprise me a lot, you have lost a loyal admirer of Cinnamon...

When taking decisions whatsoever, you engage your reputation and that of Linux Mint.

Regards.

**Comment by martindurant** [comment]
(I do not represent linuxmint)

It seems to me that you noted a problem, and first got a workaround then a solution. Next, you want to complain about other things. You may have valid points, but they don't belong in this thread. From my experience with LM, I can say that they really care about making most users happy most of the time, but no system can satisfy everyone.
In LM, you do not need to accept updates...
