### ISSUE TITLE
Add support for current kernel backport in the ISO image

### ISSUE THREAD

**Issue by ovari** [linuxmint/lmde-4-cinnamon-beta#22]
Click `Start LMDE 4 Cinnamon 64-bit`

```
error: /live/vmlinuz has invalid signature.
error: you need to load the kernel first.

Press any key to continue…
```

After a few seconds, with no key press, the menu returns.

The other options produce the same result.

ASUS VivoBook Flip Touchscreen 2-in-1 Laptop
Max eMMC speed lowered to 200 as this is required for kernels lower than 5.3.

Thank you

**Comment by Phil995511** [comment]
First check the integrity of the downloaded LMDE 4 ISO image :

https://mirrors.evowise.com/linuxmint/testing/sha256sum.txt

After try to install LMDE and if it's possible obtain kernel v 5.4 : 

https://forums.linuxmint.com/viewtopic.php?p=1768375#p1768375

**Comment by ovari** [comment]
Yes the ISO image integrity was correct.
`eafb5e3836918dd9f8752d888dd392038f9783066c4a607df06eeb1a4c410c37  lmde-4-cinnamon-64bit-beta.iso`

We were trying to start LMDE 4 from the live USB which was created from the ISO. When starting booting from the USB stick, then selecting `Start LMDE 4 Cinnamon 64-bit` the error message was shown. Can the kernel on a live USB stick be updated?

Thank you

**Comment by Phil995511** [comment]
Updating the kernel before an installation seems difficult to achieve in the current state of things. Clem should offer us the possibility of booting on kernel 4.19 or directly on kernel 5.x (current kernel backport) which would be wonderful ... I hope he will offer this option for you as well as for other people like you who do not succeed to start with kernel 4.19 !!!

**Comment by ovari** [comment]
Linux kernel <= `5.2` does not works

Linux kernel `5.3.0-23-generic` works
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1818407

**Comment by Phil995511** [comment]
The current kernel backport is 5.4...

I hope Clem will allow us to upgrade the kernet before installation, we must wait for its response.

Or you have to search on the internet how to update an ISO but it must be complicated...

Edited 28.02.2020

The best thing would be to be able to add a function to grub so that it can download the latest backports kernel and boot from it. This function is important if you want the LMDE 4 ISO to always be able to be used in time... Or simpler, an additional choice to boot the 5.4 kernel from grub.

**Comment by clefebvre** [comment]
Multiple kernels is outside of the scope for this release. It's something we tried for 19.3 and we weren't successful. We may look into it again in the future but it's not planned for LMDE 4.

That said, this isn't about the kernel version..

error: /live/vmlinuz has invalid signature.

That's the kind of error you get when SecureBoot is enabled and the ISO isn't properly signed. That was the case for the BETA. We've been working on fixing support for SecureBoot these past few days and this is coming for the stable ISO.

**Comment by Phil995511** [comment]
It’s really a shame.

Fortunately it is possible to make a :

apt update && apt install -t buster-backports linux-image-amd64 && apt install -t buster-backports linux-headers-amd64 && apt install -t buster-backports firmware-linux firmware-linux-nonfree && reboot 

But that doesn't help our friend Ovari...
