### ISSUE TITLE
Pinta Image application Install Issue

### ISSUE THREAD

**Issue by edover2019** [linuxmint/lmde-4-cinnamon-beta#25]
Hello,

I use the Pinta image application, and noticed that it is not available when installing it from the command line.

I ran apt-get update, but Pinta package is not found. Is this normal? Does something have to be tweaked somewhere in the repos?

This is the error I get when installing from the command line:

**Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pinta is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'pinta' has no installation candidate**

Pinta is available in the Software Manager and installs fine. But should it not also be available for install in the command line?

Thanks.

**Comment by xenopeek** [comment]
Hi,

Yes this is normal but I can understand the confusion. LMDE 4's Software Manager lets you install software from two different types of software repositories:

- configured APT repositories that also `apt-get` installs software from;
- configured [flatpak](https://www.flatpak.org/) repositories.

With the default LMDE 4 repositories Pinta is only found in the second, the [Flathub](https://flathub.org/) flatpak repository. Hence `apt-get` doesn't find it.

Flathub makes more and newer software available for installation on Linux distros. In Software Manager you can see a clue for the fact that Pinta is installed from a flatpak repository as on the Pinta page it says "Details (Flatpak)" and then lists information about the default flatpak repository (Flathub).

You can also install Pinta from the command line by using the `flatpak` command. See the Pinta page on Flathub for the command you need: https://flathub.org/apps/details/com.github.PintaProject.Pinta

**Comment by edover2019** [comment]
> Hi,
> 
> Yes this is normal but I can understand the confusion. LMDE 4's Software Manager lets you install software from two different types of software repositories:
> 
>     * configured APT repositories that also `apt-get` installs software from;
> 
>     * configured [flatpak](https://www.flatpak.org/) repositories.
> 
> 
> With the default LMDE 4 repositories Pinta is only found in the second, the [Flathub](https://flathub.org/) flatpak repository. Hence `apt-get` doesn't find it.
> 
> Flathub makes more and newer software available for installation on Linux distros. In Software Manager you can see a clue for the fact that Pinta is installed from a flatpak repository as on the Pinta page it says "Details (Flatpak)" and then lists information about the default flatpak repository (Flathub).
> 
> You can also install Pinta from the command line by using the `flatpak` command. See the Pinta page on Flathub for the command you need: https://flathub.org/apps/details/com.github.PintaProject.Pinta

Ah, okay. Got it. Thanks!
