### ISSUE TITLE
unexpected Cinnamon fallback mode

### ISSUE THREAD

**Issue by morton-f** [linuxmint/lmde-4-cinnamon-beta#27]
After disabling _accounts-daemon.service_ Cinnamon switches to the fallback mode.
**Edit:** Cinnamon crashes to fallback mode in the traditional desktop layout. 
How to reproduce:
```
sudo systemctl stop accounts-daemon.service
sudo systemctl disable accounts-daemon.service
sudo systemctl mask accounts-daemon.service
Logout
Login
```
There is no fallback mode after disabling the same service in Debian stable and Debian testing (same Cinnamon version). 

Re _accounts-daemon.service_ itself, though I can't conceive any practical use of it, I afraid it is used by the screensaver here. Edit: If it is so then probably it is not an issue and we'd see the same behaviour in Mint Cinnamon. 

_**LMDE 4**_
Cinnamon 4.4.8
systemd 241
4.19.0-8-amd64 SMP Debian 4.19.98-1 (2020-01-26)
NVIDIA GP108 driver: nvidia v: 418.74 
X.Org 1.20.4
OpenGL: renderer: GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 418.74 

**_Debian bullseye/sid_** - no issue
Cinnamon 4.4.8
systemd 244 (244.3-1)
4.19.0-5-amd64 SMP Debian 4.19.37-6 (2019-07-18)
NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 410.93 
X.Org 1.20.7
OpenGL: renderer: GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 410.93 

**_Debian 10 buster_** - no issue
systemd 241
Cinnamon 3.8.8
4.19.0-5-amd64 SMP Debian 4.19.37-5+deb10u2 (2019-08-08)
NVIDIA GP108 driver: nvidia v: 418.74 
X.Org 1.20.4
OpenGL: renderer: GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 418.74 

[log_messages.txt](https://github.com/linuxmint/lmde-4-cinnamon-beta/files/4266455/log_messages.txt)
[journalctl.txt](https://github.com/linuxmint/lmde-4-cinnamon-beta/files/4266488/journalctl.txt)

**Comment by mtwebster** [comment]
It's used by a number of things - the screensaver, the login manager (lightdm), cinnamon settings, and more - it's a generic (cross-distro) interface to allow programs to discover user-related information (full user name, user image, current desktop background, etc..)

check out:
```
apt-cache show accountsservice
apt-cache rdepends accountsservice
```
https://www.freedesktop.org/wiki/Software/AccountsService/

Is there any specific reason you want to disable it?

**Comment by morton-f** [comment]
@ mtwebster  It is one of several unnecessary for me services which I always disable in Debian Cinnamon without any consequences. Assuming (wrongly) this issue is an abnormality comparing to Debian as it would be started by DBus on demand when something actually needs it. Thank you for the clarification!
