### ISSUE TITLE
Backup Ideea

### ISSUE THREAD

**Issue by paulvonlux** [linuxmint/lmde-4-cinnamon-beta#28]
Make a backup program or integrate in the actual one ALL the settings of the cinnamon, themes, colors, settings, menu' etc, that would be a great idea, for example when i install a fresh LMDE i would only import the old settings and the looks / settings etc would be of the previous personal customised LMDE instalation.

**Comment by Phil995511** [comment]
Good idea for save / importing the Cinnamon settings to a new pc for fresh install :)  

If you make a reinstall of Mint without formatting the /home partition all settings are preserved.

TimeShift are a integrated backup software of Mint, you have also an option on Gnome-Disk for creating / restorating a image disk of your partitions.

**Comment by paulvonlux** [comment]
yes but i want to put a profile in multiple PC's

**Comment by clefebvre** [comment]
mintbackup can help with that, it's installed by default also.

**Comment by Phil995511** [comment]
Paulvonlux would like a possibility to create a .conf file for export it configuration of Cinnamon to an another pc.

It's is a verry good idea for my but you are the leader of this distribution... this is for you to decide.
