### ISSUE TITLE
btrfs-setup not bootable if using gpt partitioning with a single btrfs-partition

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/lmde-4-cinnamon-beta#3]
(a test-case I did not cover myself when submitting the initials fix -> have to blame myself to some extend :-)  )

1) create fresh partition table  using **gpt**  instead of msdos/mbr-style
2) create single btrfs-partition and accept changes
3) run installer ... manual partitioning - assign  partition to /@   using btrfs
4) finish install and reboot
system does hang on reboot (hard reset and reboot does not help)  - at the first sight the created grub.cfg does look ok.
My supspect is grub disliking to have /boot being located at a btrfs  with gpt as ...

This does work:
1) create fresh partition table  using **gpt**  instead of msdos/mbr-style
2) create **two** partitions partition 1) ext4 500 MB is enough partition 2) btrfs as main partition for the rest
3) run installer ... manual partitioning - assign  partition 1 (ext4) /boot , assing partition 2 (btrfs) to /@
4) finish install and reboot
Does work - timeshift works too

Using a single btfs partition using msdos/mbr-style  and assigning to /@  does boot, timeshift does work too

**Comment by clefebvre** [comment]
Hi @orcus-de, is that a grub limitation or something? Sorry, I've to admit although we support btrfs in live-installer, it's not something we test or know much about.

**Comment by orcus-de** [comment]
:) shh... I hoped you had time to paly more with btfrs 

I've to admit that I didn't look deeper into it - but might be I got the time to dig deeper the next some nights - will report back in any case.

What's surprising that it does work with mbr/msdos partition-layout and not with gpt ... and yes grub has some personal dislike with btrfs - there are explicit tests from grub "against" (literally) some filesystems.

At least there is the typical workaround using boot as ext4 to bypass grub being funky about btrfs.

**Comment by orcus-de** [comment]
Found it :-) It was a **Layer 8 bug** = I focused too much on btrfs being the problem.

I left out the important detail, that the VM was executed in BIOS mode, and using gpt a BIOS partition is absolutely necessary ... (apparently a combination of a ext4 boot partition and btrfs partition is working too for some reason - see above)

With gparted:
a) Create partition 1) ** fat32 100 MB **
b) Create partition 2) ** btrfs **
Apply changes
c) afterwards set the attributes of partition 1) to ** BIOS Boot **

Run the installer:
d) Assign partition 2) to /@
e) grub-install takes place on harddisk device (no partition)

=> the issue can be closed, **BUT**

The installation program should check whether a BIOS partition is required and show a corresponding warning before actually running it.

And when I remember some unsolvable IRC user installation problems in the past, I think more people are affected:

Usually a Windows dual boot setup is used  (very likely with pre-existing gpt partitioning) / since some users occasionally switch the computer to BIOS / legacy mode, they end up in exactly the same situation and the machine is no longer bootable from HDD/SSD:
 grub-menu is not accessible
 machine can only be rebooted by REISUB or by a cold start

(after selecting a different boot-device windows / live-mint - they can get back to some OS at least - but thinking about unexperienced users sitting at their seemingly dead machine after trying to install mint   ... will likely be not this funny for them)

The good part of the story is:
grub-install already issues a warning if it is executed by a terminal => error handling can take place here at the latest, although a preliminary test would be much more preferable for the user.

```
grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
grub-install: error: filesystem `btrfs' doesn't support blocklists.
```

**Comment by clefebvre** [comment]
I was looking at LVM and LUKS in manual mode with @monsta also... there are a lot of niche cases where the installer could show a little more info and warn the user or restrict his actions... or explain why something shouldn't be possible. For instance, we don't alert if a partition is busy... or if it's part of LVM right now.

I think we'll go ahead with the release for now but between now and LMDE 5 we'll welcome PRs and push commits to make live-installer more robust on these kind of things.
