### ISSUE TITLE
Laptop with Nvidia and Intel GPU

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-4-cinnamon-beta#30]
I regret that you did not want to implement the necessary drivers for this (https://blog.linuxmint.com/?p=3860#comment-153563).

However, it would be desirable that you implement an facultative option allowing to blacklist the Intel gpu (which is not possible to disabled it into the bios) so as to force the boot on the Nvidia gpu with support of it driver.

Thank you in advance and have a good weekend for you and your family

**Comment by Phil995511** [comment]
If it can help you do something here is a little tutorial

https://github.com/delta-one/dell-xps-15-9570-debian-linux

Regards.

**Comment by clefebvre** [comment]
Maybe in a future release. For now this isn't part of the scope for LMDE. Driver Manager and nvidia-prime-applet rely on ubuntu-drivers and nvidia-prime which are Ubuntu specific and which we didn't port.

**Comment by Phil995511** [comment]
It's really unfortunate, implementing Optimus or Bumblebee would certainly be easy for you !! It's a hassle for us.

https://wiki.debian.org/NvidiaGraphicsDrivers/Optimus
