### ISSUE TITLE
NVIDIA: Bump to backports version (430)

### ISSUE THREAD

**Issue by bmccann16** [linuxmint/lmde-4-cinnamon-beta#33]
Boot fails with an NVIDIA 2070 Super GPU running with an Intel 6850K CPU (which has no internal GPU). Screen goes blank like X windows is trying to start and then comes back with a single underline text cursor. Rinse and repeat ad infinitum.

I disabled 'splash quiet' while booting and saw that the NVIDIA driver installed during boot (which, BTW, is a cool trick) is version 418.xx. The new-ish 'SUPER' series NVIDIA GPUs require at least driver version [430.34](https://www.nvidia.com/Download/driverResults.aspx/148589/en-us) or later. I imagine the 418 series drivers are dying when they encounter the 2070 super.

Please upgrade the NVIDIA driver used by your installation media to version 430.34 or later to ensure these newer NVIDIA cards are supported. For example, Debian Buster backports currently has version 430.64-4~bpo10+1. This should work.

I hope you can use a driver from Buster Backports for what is otherwise a pure Debian 10 base for LMDE 4. You'll have to use the 430.64 driver from backports in both the install media *and* on the target system during installation. Otherwise, if you just install NVIDIA driver 418 straight from Debian 10, the newly installed system won't be able to boot for exactly the same reason described above.

**Comment by clefebvre** [comment]
This is fixed for the next ISO, the NVIDIA driver is now prepared from the backports repository (at the moment this is version 440).
