### ISSUE TITLE
cinnamon: systray tooltips show under the panel

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#34]
on the far right of the taskbar (I'm not sure if that is the correct name for the right hand side) where the date, volume, internet, update manager, and bluetooth icons are, tool tips appear if you hover over them with your mouse.
However, for Gnome Calendar "reminders" icon, which is a red clock, the tool tip appears UNDER the icon (and under the taskbar) - so you can't actually see what is says.

**Comment by clefebvre** [comment]
Dev note: This is detected by Cinnamon as a systray icon (not Xapp) "evolution-alarm-notify".... probably a direct Gtk.StatusIcon consumer..

**Comment by clefebvre** [comment]
OK, this is part of evolution-data-server (/usr/lib/evolution/evolution-data-server/evolution-alarm-notify).

**Comment by clefebvre** [comment]
I can't find anything in evolution-alarm-notify's code that would position the tooltip like that...

**Comment by clefebvre** [comment]
ah wait... it's a general issue:

- Remove the network applet
- See the nm applet show up
- Hover.. the tooltip is below the panel

Looks like orientation is broken in Cinnamon for systray.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/muffin/commit/d80c0dc898b665fab3d78095664b3c245c0ee5ba. 
We'll be pushing this fix as a package update post-release.
