### ISSUE TITLE
Icon for "Themes" & "Qt5 Settings"

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#35]
In the start menu, under the preferences category, the icon is the same for Themes and Qt5 Settings.

**Comment by clefebvre** [comment]
It's not ideal, unfortunately there's no widespread icon we can use for Qt.. there's nothing in GNOME or Adwaita for it...

We could make it use the Mint-Y icon for qtconfig-qt4, but that would look out of place in other themes.
