### ISSUE TITLE
Install Hangs

### ISSUE THREAD

**Issue by gh4wi** [linuxmint/lmde-4-cinnamon-beta#36]
When installing LDME-4-Cinnamon-beta to PC /w WD 80gb HDD on Sata 2 using the encrypt HDD feature, the install hangs creating /dev/sda partitions. Installing to the same hardware without the encrypt HDD feature woks OK. Tried two different drives with same result.

**Comment by clefebvre** [comment]
Try in terminal (sudo live-installer) to see where it hangs and if it's waiting for something..

**Comment by clefebvre** [comment]
I believe this is fixed. We now show an error dialog when the partition table can't properly be overwritten.
