### ISSUE TITLE
Optimus or Bumblebee on LMDE 4

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-4-cinnamon-beta#38]
Please implementing Optimus or Bumblebee on LMDE 4, would certainly be easy for you, it's a hassle for us to make work it.

https://wiki.debian.org/NvidiaGraphicsDrivers/Optimus

**Comment by clefebvre** [comment]
Thanks Phil, we might port more features into LMDE 5, but for now this is outside of the scope for LMDE 4.
