### ISSUE TITLE
btrfs: Timeshift does not recognize BTRFS system disk

### ISSUE THREAD

**Issue by navyguns** [linuxmint/lmde-4-cinnamon-beta#39]
Root and Home partition are both BTRFS. Timeshift does not recognize either as a system disk. Give warning "Selected snapshot device is not a system disk"

**Comment by orcus-de** [comment]
hi navyguns,
I suspect that you missed the note at the installer to select /@ (and optional /@home) if you want to make use of timeshift with btrfs-partitions.
Your current /etc/fstab  -entry should read like this (besides the uuid) if you did use the subvolumes correctly:

UUID=2a3b7413-a84a-47ca-99e3-f7e1baa8894c	/	btrfs	rw,subvol=/@	00

related screen-shots (might help for the next try): https://imgur.com/a/CflwU4y

**Comment by navyguns** [comment]
Thanks. I did miss that. I have / and not /@ and /home and not /@home. This must be specific to LMDE as I don't recall seeing this on Mint 19.3 where I have the same setup.

**Comment by monsta** [comment]
I think Timeshift should behave the same in both distros... doesn't your `/etc/fstab` in Mint 19.3 have `subvol=/@` and `subvol=/@home` parameters?

**Comment by navyguns** [comment]
It does. The difference being that Mint 19.3 just made those entries on installation without requiring intervention on my part.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by monsta** [comment]
Ok, so Ubiquity must have done it automatically.
