### ISSUE TITLE
No encryption of entire system in manual partitioning mode

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/lmde-4-cinnamon-beta#4]
Dear Clem, LMDE 4 beta runs very well. No problems so far. I love it. Excellent job and thank you very much for your great work.

Nice to see, you added LVM and encryption of the entire system to the automated installation. It is, however, missing in the manual partitioning mode. Many users like me have other systems on the hard drive, so wiping the complete disk for an automated installation is not an option. The ability to encrypt the entire system including root directory (not only /home) is essential nowadays. Would it be possible to add this valuable feature to the manual partitioning mode? LMDE 3 also offered Calamares, which was capable of doing so (without LVM, though). Unfortunately now in LMDE 4 Calamares is dropped; therefore another possible solution would be to include Calamares again.

Best regards

**Comment by clefebvre** [comment]
Hi @harlekin777, I'm sorry that's outside of the scope for this release. Note that we have `live-installer-expert-mode` for niche cases like these one.
