### ISSUE TITLE
expert-mode

### ISSUE THREAD

**Issue by CyberDomovoy** [linuxmint/lmde-4-cinnamon-beta#40]
Where is it?

Even with "manual" partitioning, it lacks the ability to assign btrfs subvolumes to different mountpoint (/@, /@home).

In any case, not having the ability to partition and mount /target ourselves is, imho, a bad, bad thing.
Please allow us to to "expert install"

**Comment by clefebvre** [comment]
It's there: sudo live-installer-expert-mode, then choose manual and click the Expert mode button.

Note that there's an issue in the BETA and the Next button doesn't show up... this is fixed in Git and we'll push an updated installer with this fix tomorrow towards the repositories.

**Comment by CyberDomovoy** [comment]
imho this should be the default mode.
All that it changes is a simple "expert" button, and it is only visible in "manual partitioning". If you get to manual partitioning, you're supposed to know what you're doing anyway, so having the choice to do it all the way seems right to me.

**Comment by monsta** [comment]
No expert mode is needed for that. Assigning `/@` and `/@home` can be done via Edit menu item in the right-click menu.

![edit-partition](https://user-images.githubusercontent.com/5138986/76143404-42c13b00-6088-11ea-84d6-06d624a7124b.png)

**Comment by CyberDomovoy** [comment]
Yes but if both @ and @home are on the same partition (2 subvolumes, 1 btrfs), then i can choose only one (i.e. select '/@' on sda1, i can't assign a mountpoint for '/@home' on sda1)

**Comment by monsta** [comment]
@orcus-de: have to bother you once again... so it's possible to have both subvolumes on a single partition?

**Comment by orcus-de** [comment]
np monsta - feel free to contact me any time ..
@topic:
1) I never did even think about having multiple subvolumes at a single partition.
2) I doubt this will work with the current installer as you are only able to assign a mountpoint per partition == changing this would require a major rewrite of the complete installer.
3) Additionally: I wont dare to bet if timeshift would be able to use such a setup (my submitted update for the installer at that time have only served the sole purpose to make the btfs-snapshot feature available to timeshift - which did/does insist on subvolumes).

PS: as I do not read my emails this often :-)  // if you need some faster response: I often hang around at the #linuxmint-help irc-channel .. 
If my nick is switched to orcus-afk -  I often read the channels while I'm working here: message me using the current nickname will ring an alarm...

**Comment by monsta** [comment]
Ok, thanks. Maybe we can learn from Ubiquity about managing such setup.
