### ISSUE TITLE
language/keyboard

### ISSUE THREAD

**Issue by CyberDomovoy** [linuxmint/lmde-4-cinnamon-beta#41]
After choosing a french keyboard during installation, the layout is "English (US)" after reboot.
In fact, the french layout is not even available as a choice.

It seems the system language is not installed either, i had to install french language from the preferences menu

I cannot choose another keyboard layout from lightdm (only en-us is present)

**Comment by clefebvre** [comment]
I can't reproduce this issue. The use case works perfectly for me:

- I choose French/French in the installer
- The summary screen confirms my choice of keyboard layout
- Post-install the session is using a French keyboard
- The system keyboard is also set to French (/etc/default/keyboard)

Note: The keyboard indicator in the login screen is only a visual indication of the system keyboard, it's not meant to let you select a different layout. To do so, you need to edit /etc/default/keyboard.

**Comment by CyberDomovoy** [comment]
Hmmm, maybe i did something wrong, will check again next time i do an install
