### ISSUE TITLE
LMDE runs perfect on i5-7300U, but not on Ryzen5-3500U APU

### ISSUE THREAD

**Issue by Joerg-Lorenz** [linuxmint/lmde-4-cinnamon-beta#43]
Thanks for this new, great distro, Clem. 

Tried it on a few computers, and the results look very nice, but it fails on the relatively new Ryzen Notebook APUs. Doesnt boot neither in compatibilty mode, nor regular. Switching to GUI /Boot greeter seems to be the issue, as the bootup shows the regular messages (network manager etc.). CLI works (strg-alt-F1).  According to the syslog lightdm service starts, throws a warning and stops again, gives up after some retries. Driver AMDGPU is there, writing an xorg.conf manually works and recognizes the driver. But the lightdm issue remains.

Other: LM 19.3 boots fine with the hardware. 

It appears as if the settings of debbie could be modernized for the APUs. 
If you need more input, I am happy to help.

**Comment by clefebvre** [comment]
Hi Joerg,

I think it's down to the kernel being too old. We can't upgrade it unfortunately, we want to stick to the official Debian kernel so you can get security updates and there's only one supported branch for this in Debian.

We're experimenting with the idea of shipping with alternative kernels in the ISO, but this won't be ready for LMDE 4.
