### ISSUE TITLE
Can't stop pulseaudio

### ISSUE THREAD

**Issue by eblanca** [linuxmint/lmde-4-cinnamon-beta#44]
This is needed in order to get more diagnostic for another issue (almost sure it's a bug).
Anyway, I have the "client.conf" file into ~/.config/pulse/ directory, and it has
`autospawn=no`
inside as in my everyday distro (lmde3) this prevents pulse from re-starting after any kill.
I launched
`pulseaudio --kill`
and pulseaudio stops, then re-starts in a few seconds, as well as
`killall pulseaudio`
with the same result.
I just would like to stop it and re-start in a command line to be able to see any debug messages it prints out.
Is there a further (new) command to stop it? I'm not loving pulseaudio at all, and this makes me even less prone to appreciate it.

**Comment by clefebvre** [comment]
Hi @eblanca,

According to https://wiki.debian.org/PulseAudio#Disabling_daemon_autospawn this should work the way you interpreted. It looks like a bug to me but it seems upstream from us. I'd suggest testing to confirm if it also affects Debian 10, and if it does reporting this to Debian directly.
