### ISSUE TITLE
Add support for secure boot

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/lmde-4-cinnamon-beta#5]
Debian 10 (finally!) introduced support for secure boot. In LM 19 (and before) secure boot was already supported, presumably by using Ubuntu's Shim. So I imagine, it should be possible now to do the same in LMDE 4 by using Debian's Shim. Imho it is an important feature.

**Comment by clefebvre** [comment]
This is coming in the stable ISO. We got it working today.

**Comment by harlekin777** [comment]
Dear Clem,
that is excellent. Thank you very much!!! I really appreciate your great work!
