### ISSUE TITLE
live-installer: translated messages incomplete

### ISSUE THREAD

**Issue by eblanca** [linuxmint/lmde-4-cinnamon-beta#51]
Once language is selected in the very first dialog I would expect any sentences to be in my preferred language, but this is (still) not the case.

![Completa_2](https://user-images.githubusercontent.com/1640886/76208851-cbfb7d80-6200-11ea-905a-e9daa09f5d46.png)

The 'Next' button also needs translation:
![Tasto_Next](https://user-images.githubusercontent.com/1640886/76208771-a4a4b080-6200-11ea-98e5-49ac45687cf3.png)

Further, the whole page about partition selection/customization needs translation (but this may be due to it being a separated application).

**Comment by clefebvre** [comment]
This is fixed in stable.
