### ISSUE TITLE
LMDE RAM CONSUMPTION

### ISSUE THREAD

**Issue by paulvonlux** [linuxmint/lmde-4-cinnamon-beta#58]
Idle RAM consumption for LMDE 4 is **780/790/800mb**. For example Lubuntu 19.10 only uses **320/350MB** when idle. i hope that the memory consumption figure can be lowered. Use C and ASSEMBLY to lower that where you can.

**Comment by alan7000** [comment]
The difference is on the desktop environment used between LMDE 4 and Lubuntu 19.10. I remind you that LMDE uses cinnamon while Lubuntu uses LXDE.

**Comment by paulvonlux** [comment]
> The difference is on the desktop environment used between LMDE 4 and Lubuntu 19.10. I remind you that LMDE uses cinnamon while Lubuntu uses LXDE
I know what uses what, i just want a lower RAM consumption on LMDE 4

**Comment by paulvonlux** [comment]
> The difference is on the desktop environment used between LMDE 4 and Lubuntu 19.10. I remind you that LMDE uses cinnamon while Lubuntu uses LXDE.

I know what uses what, i just want a lower RAM consumption on LMDE 4

**Comment by paulvonlux** [comment]
> The difference is on the desktop environment used between LMDE 4 and Lubuntu 19.10. I remind you that LMDE uses cinnamon while Lubuntu uses LXDE.

Also you are a noob Lubuntu does not use LXDE... It uses LXQt

**Comment by JosephMcc** [comment]
Please refrain from name calling or anything personal. This isn't the place for that. The memory usage you're seeing looks about right to me for a Mint/Cinnamon install. It's actually a bit lower then what I typically  see under Ubuntu based Mint.

**Comment by paulvonlux** [comment]
> Please refrain from name calling or anything personal. This isn't the place for that. The memory usage you're seeing looks about right to me for a Mint/Cinnamon install. It's actually a bit lower then what I typically see under Ubuntu based Mint.

Because it's based on Debian and not Ubuntu, and please refrain from  giving me advices, give advices to alan7000 . Also NomadBSD uses even less / or the same as Lubuntu 19.10 because the UNIX systems have a better memory management system
