### ISSUE TITLE
live-installer: Timezone menus don't fit in 768px.

### ISSUE THREAD

**Issue by eblanca** [linuxmint/lmde-4-cinnamon-beta#6]
I'm installing lmde4 into a VM, using the minimum suggested resolution 1024x768.
Now, when selecting the timezone, many sub-menus have so many entries, the list gets longer than the screen height. BUT the submenu doesn't scroll, so I am unable to select any entries below the virtual screen limit.

Edit: using keyboard cursor keys doesn't help in any ways.

**Comment by harlekin777** [comment]
I can confirm this bug on a real computer.

**Comment by Rosssen** [comment]
I can confirm this bug too.

**Comment by mtwebster** [comment]
Fixed: https://github.com/linuxmint/live-installer/commit/43e7da77f4a61992d7c1f012c34760f308c8da5d
