### ISSUE TITLE
Sound Applet

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#9]
Clem,
An issue that I found, while ordinarily not specific to Debbie, as you have chosen the kernel that you have, then it is related as Cindy did not have the issue. I have posted it here...
https://github.com/linuxmint/cinnamon/issues/7578#issuecomment-590477695

In my Sound Applet, "HDMI/Display Port 2 Built in Audio" is no longer listed in LMDE Debbie.
I reinstalled Cindy, and and the DVI connection into my Dell laptop is listed there as "HDMI/Display Port 2 Built in Audio" (well up to and including 4.16.1 kernel, it wouldn't allow me install more recent Kernels). It is also listed in Linux Mint 19.2 for kernel 4.15.0-88 -> but not Linux Mint 19.3.

On Debbie, I have installed the following kernels from https://kernel.ubuntu.com/~kernel-ppa/mainline/, -> 4.18.1, 4.18.5, 4.18.10, 4.18.15 and 4.18.19 and the HDMI/Display Port was again listed perfectly. (I'm unable to get kernel 4.18.20 up and running.)

However, with Kernel 4.19.0 (any of the release candidates) it won't appear.

This would lead me to assume it is something to do with more recent kernels than the desktop environment - so if i use LMDE Debbie or Linux Mint 19.3, I must keep the 4.18.19 kernel or is there a workaround.

**Comment by clefebvre** [comment]
In LMDE 4 you can only use 4.19... that's what Debian supports in terms of security updates. If you use anything else you're on your own in regards to security updates.

In Mint 19.x you can use either the HWE kernel (which is 5.3 at the moment) or the LTS kernel (which is 4.15). Mint 19.3 comes with kernel 5.3, you can install 4.15 and remove 5.3 if you want and you'll continue to get security updates for 4.15.
